; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = ./boards

[env:T-DisplayS3]
board = lilygo-t-displays3
upload_speed = 921600
monitor_speed = 115200
framework = arduino
debug_tool = esp-builtin
upload_protocol = esptool
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
build_unflags = -Os
build_flags = 
	-DBOARD_HAS_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
	-DCONFIG_ESP_SYSTEM_PANIC_HALT=y
	-DCONFIG_ESP_SYSTEM_PANIC_REBOOT=n
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_CONF_SKIP ; Configure LVGL in platformio.ini instead of lv_conf.h - https://github.com/lvgl/lv_platformio/issues/28
	; Configuration instructions: https://docs.lvgl.io/master/porting/project.html
	-DLV_COLOR_DEPTH=16
	-DLV_USE_ST7789
	-DLV_USE_LOG
	-DLV_LOG_LEVEL=LV_LOG_LEVEL_INFO
	-DLV_USE_ASSERT_NULL
	-DLV_FONT_MONTSERRAT_24
	-DBOARD_HAS_PSRAM ; Enable PSRAM for the display buffer

lib_extra_dirs = ${PROJECT_DIR}
lib_deps = 
	adafruit/Adafruit BusIO
	adafruit/Adafruit TLV320 I2S
	earlephilhower/ESP8266Audio
	adafruit/SdFat - Adafruit Fork@^2.3.54
	lvgl/lvgl@^9.5.0
debug_init_break = break setup
build_type = debug
monitor_filters = esp32_exception_decoder, colorize, time ; debug